package leyline.game.codes

/** Annotation detail key constants — single source of truth for proto detail key strings. */
object DetailKeys {
    const val ZONE_SRC = "zone_src"
    const val ZONE_DEST = "zone_dest"
    const val CATEGORY = "category"
    const val GRPID = "grpid"
    const val REPLACEMENT_SOURCE_ZCID = "ReplacementSourceZcid"
    const val COLOR_IDENTITY = "ColorIdentity"
    const val COST_INCREASE = "CostIncrease"
    const val PHASE = "phase"
    const val STEP = "step"
    const val ORIG_ID = "orig_id"
    const val NEW_ID = "new_id"
    const val ACTION_TYPE = "actionType"
    const val ABILITY_GRP_ID = "abilityGrpId"
    const val ABILITY_GRP_IDS = "abilityGRPIDs"
    const val ID = "id"
    const val COLOR = "color"
    const val SUBSTITUTION_GRPID = "substitution_grpid"
    const val MANA_SPEC_TYPE_DOES_NOT_EMPTY = "ManaSpecType_DoesNotEmpty"
    const val TAPPED = "tapped"
    const val SOURCE_ZONE = "source_zone"
    const val DAMAGE = "damage"
    const val TYPE = "type"
    const val MARK_DAMAGE = "markDamage"
    const val LIFE = "life"
    const val REASON = "reason"
    const val SHOULDNT_PLAY_REASON = "Reason"
    const val LEVEL = "Level"

    /** Uppercase REASON variant — used on the persistent `FaceDown`
     *  annotation (`{ "key": "REASON", valueInt32: [6/8/5] }` for
     *  Disguise/Morph/Manifest). Distinct from [REASON] (lowercase) which
     *  is used for transient `LossOfGame` and similar annotations. */
    const val REASON_UPPER = "REASON"
    const val COUNTER_TYPE = "counter_type"
    const val TRANSACTION_AMOUNT = "transaction_amount"
    const val TOP_COUNT = "topCount"
    const val BOTTOM_COUNT = "bottomCount"
    const val TOP_IDS = "topIds"
    const val BOTTOM_IDS = "bottomIds"
    const val OLD_IDS = "OldIds"
    const val NEW_IDS = "NewIds"
    const val COUNT = "count"
    const val EFFECT_ID = "effect_id"
    const val UNIQUE_ABILITY_ID = "UniqueAbilityId"
    const val ORIGINAL_ABILITY_OBJECT_ZCID = "originalAbilityObjectZcid"
    const val ABILITY_GRP_ID_UPPER = "AbilityGrpId"
    const val USES_REMAINING = "UsesRemaining"
    const val DESIGNATION_TYPE = "DesignationType"
    const val CONTROLLER_ID = "ControllerId"
    const val ACTIVE_PLAYER_SPELL_COUNT = "ActivePlayerSpellCount"
    const val PREPARED_COPY_ZCID = "PreparedCopyZcid"
    const val SOURCE_ABILITY_GRPID = "sourceAbilityGRPID"
    const val INVALIDATING_GRPID = "invalidating_grpid"
    const val LINK_TYPE = "LinkType"
    const val CHOOSE_LINK_TYPE = "ChooseLinkType"
    const val CHOICE_VALUE = "Choice_Value"
    const val CHOICE_DOMAIN = "Choice_Domain"
    const val CHOICE_SENTIMENT = "Choice_Sentiment"
    const val COLORS = "colors"
    const val INDEX = "index"
    const val PROMPT_ID = "promptId"
    const val CHOSEN_COST_PROMPT_ID = "chosenCostPromptId"
    const val PROMPT_PARAMETERS = "promptParameters"
    const val DISTRIBUTIONS = "distributions"
    const val POWER = "power"
    const val TOUGHNESS = "toughness"
    const val DISABLE = "Disable"
    const val TEMPORARY_ZONE_TRANSFER = "TemporaryZoneTransfer"
    const val VALUE = "value"
    const val ABILITY_WORD_NAME = "AbilityWordName"
    const val THRESHOLD = "threshold"
    const val QUALIFICATION_TYPE = "QualificationType"
    const val QUALIFICATION_SUBTYPE = "QualificationSubtype"
    const val SOURCE_PARENT = "SourceParent"
    const val CANT_BLOCK_OBJECTS = "CantBlockObjects"
    const val CANT_BE_BLOCKED_BY_OBJECTS = "CantBeBlockedByObjects"
    const val ALTERNATIVE_GRP_ID = "alternativeGrpId"
    const val ALTERNATE_COST_GRP_ID = "alternateCostGrpId"
    const val CAST_ABILITY_GRP_ID = "castAbilityGrpId"
    const val KICKER_ABILITY_GRP_ID = "kickerAbilityGrpId"
    const val ADDITIONAL_COST_GRP_ID = "additionalCostGrpId"
    const val REMOVES_FROM_ZONE = "removesFromZone"
    const val IS_TOP = "isTop"
    const val COIN_FLIP_RESULT = "CoinFlipResult"
    const val AFFECTED_OBJECTS = "affected_objects"
}
