package leyline.game.codes

import forge.game.keyword.Keyword
import forge.game.keyword.KeywordInterface
import forge.game.keyword.KeywordWithCostAndType

/** GRE AbilityType values used by both static keyword choices and temporary keyword grants. */
object KeywordGrpIds {
    /**
     * Forge keyword display names with one unambiguous GRE AbilityType counterpart.
     *
     * Generic families whose client identity depends on a parameter, such as Affinity, Protection,
     * and TypeCycling, are deliberately absent.
     */
    private val canonicalIds =
        mapOf(
            "Absorb" to 65,
            "Afflict" to 164,
            "Affinity for artifacts" to 177,
            "Affinity for auras" to 337,
            "Affinity for equipment" to 268,
            "Affinity for goats" to 396,
            "Affinity for outlaws" to 333,
            "Afterlife" to 173,
            "Aftermath" to 159,
            "Amplify" to 39,
            "Annihilator" to 87,
            "Ascend" to 165,
            "Aura swap" to 66,
            "Awaken" to 359,
            "Backup" to 287,
            "Banding" to 23,
            "Bargain" to 303,
            "Battle cry" to 92,
            "Basic landcycling" to 123,
            "Bestow" to 335,
            "Blitz" to 240,
            "Bloodthirst" to 55,
            "Bushido" to 46,
            "Buyback" to 28,
            "Cascade" to 86,
            "Casualty" to 241,
            "Champion" to 73,
            "Changeling" to 74,
            "Choose a Background" to 389,
            "Cipher" to 100,
            "Companion" to 202,
            "Compleated" to 238,
            "Conspire" to 79,
            "Convoke" to 52,
            "Crew" to 156,
            "Cumulative upkeep" to 25,
            "Cycling" to 30,
            "Dash" to 274,
            "Daybound" to 216,
            "Deathtouch" to 1,
            "Decayed" to 214,
            "Defender" to 2,
            "Delve" to 67,
            "Devour" to 83,
            "Devoid" to 151,
            "Disguise" to 307,
            "Disturb" to 215,
            "Double Strike" to 3,
            "Double team" to 253,
            "Dredge" to 53,
            "Echo" to 31,
            "Embalm" to 160,
            "Emerge" to 147,
            "Enchant" to 4,
            "Enlist" to 261,
            "Entwine" to 43,
            "Epic" to 51,
            "Equip" to 5,
            "Escape" to 199,
            "Escalate" to 153,
            "Eternalize" to 163,
            "Evoke" to 75,
            "Evolve" to 101,
            "Exalted" to 84,
            "Exploit" to 222,
            "Extort" to 102,
            "Fabricate" to 154,
            "Fading" to 33,
            "Fear" to 38,
            "Firebending" to 379,
            "First Strike" to 6,
            "Flanking" to 26,
            "Flash" to 7,
            "Flashback" to 35,
            "Flying" to 8,
            "Forestcycling" to 124,
            "Forestwalk" to 236,
            "For Mirrodin" to 267,
            "Foretell" to 208,
            "Fortify" to 68,
            "Frenzy" to 69,
            "Fuse" to 103,
            "Gift" to 342,
            "Graft" to 59,
            "Gravestorm" to 70,
            "Harmonize" to 362,
            "Haste" to 9,
            "Haunt" to 56,
            "Hexproof" to 10,
            "Hexproof from activated and triggered abilities" to 343,
            "Hexproof from black" to 193,
            "Hexproof from chosen" to 190,
            "Hexproof from each of its colors" to 403,
            "Hexproof from green" to 195,
            "Hexproof from red" to 194,
            "Hexproof from blue" to 192,
            "Hexproof from white" to 191,
            "Hideaway" to 76,
            "Horsemanship" to 32,
            "Impending" to 352,
            "Improvise" to 157,
            "Increment" to 404,
            "Indestructible" to 104,
            "Infect" to 91,
            "Ingest" to 144,
            "Intimidate" to 11,
            "Islandcycling" to 125,
            "Islandwalk" to 233,
            "Kicker" to 34,
            "Job select" to 364,
            "Jump-start" to 170,
            "Landwalk" to 16,
            "Level up" to 88,
            "Lifelink" to 12,
            "Living Weapon" to 93,
            "Madness" to 36,
            "Mayhem" to 383,
            "Melee" to 375,
            "Mentor" to 171,
            "Menace" to 142,
            "Megamorph" to 150,
            "Miracle" to 95,
            "Mobilize" to 363,
            "Modular" to 44,
            "Morph" to 37,
            "Mountaincycling" to 126,
            "Mountainwalk" to 235,
            "Multikicker" to 122,
            "Mutate" to 203,
            "Myriad" to 406,
            "Nightbound" to 217,
            "Ninjutsu" to 50,
            "Outlast" to 136,
            "Offering" to 49,
            "Offspring" to 341,
            "Overload" to 97,
            "Paradigm" to 405,
            "Partner" to 346,
            "Partner with" to 395,
            "Persist" to 80,
            "Phasing" to 27,
            "Plainscycling" to 127,
            "Plainswalk" to 232,
            "Plot" to 328,
            "Poisonous" to 71,
            "Prototype" to 263,
            "Provoke" to 40,
            "Prowess" to 137,
            "Prowl" to 77,
            "Protection from black" to 187,
            "Protection from chosen color" to 184,
            "Protection from chosen name" to 206,
            "Protection from chosen type" to 301,
            "Protection from colorless" to 288,
            "Protection from colorless or color of choice" to 289,
            "Protection from demon" to 257,
            "Protection from demons" to 257,
            "Protection from devil" to 258,
            "Protection from devils" to 258,
            "Protection from dog" to 204,
            "Protection from dogs" to 204,
            "Protection from each color" to 367,
            "Protection from each opponent" to 368,
            "Protection from everything" to 266,
            "Protection from green" to 189,
            "Protection from instant" to 339,
            "Protection from instants" to 339,
            "Protection from red" to 188,
            "Protection from sorcery" to 340,
            "Protection from sorceries" to 340,
            "Protection from spells that are one or more colors" to 381,
            "Protection from blue" to 186,
            "Protection from white" to 185,
            "Rampage" to 24,
            "Reach" to 13,
            "Read ahead" to 260,
            "Rebound" to 89,
            "Recover" to 60,
            "Reconfigure" to 237,
            "Reinforce" to 78,
            "Renown" to 358,
            "Replicate" to 57,
            "Retrace" to 82,
            "Riot" to 175,
            "Ripple" to 61,
            "Saddle" to 329,
            "Scavenge" to 98,
            "Shadow" to 29,
            "Shroud" to 22,
            "Skulk" to 143,
            "Sneak" to 394,
            "Soulbond" to 96,
            "Soulshift" to 47,
            "Specialize" to 254,
            "Spectacle" to 174,
            "Splice" to 48,
            "Split second" to 62,
            "Spree" to 330,
            "Start your engines" to 354,
            "Starting intensity" to 249,
            "Station" to 373,
            "Storied" to 408,
            "Storm" to 41,
            "Sunburst" to 45,
            "Surge" to 356,
            "Suspend" to 63,
            "Slivercycling" to 128,
            "Swampcycling" to 129,
            "Swampwalk" to 234,
            "Teamwork" to 412,
            "Tiered" to 365,
            "Toxic" to 264,
            "Training" to 220,
            "Trample" to 14,
            "Transfigure" to 72,
            "Transmute" to 54,
            "Tribute" to 135,
            "Umbra armor" to 90,
            "Undying" to 94,
            "Unearth" to 85,
            "Unleash" to 99,
            "Vanishing" to 64,
            "Vigilance" to 15,
            "Ward" to 211,
            "Warp" to 371,
            "Web-slinging" to 382,
            "Wizardcycling" to 130,
            "Wither" to 81,
        )

    private val idsByLookupName =
        canonicalIds.entries
            .associate { (name, id) -> lookupName(name) to id }
            .also { require(it.size == canonicalIds.size) { "Keyword lookup names must be unique" } }

    fun forKeyword(keyword: String): Int? = idsByLookupName[lookupName(keyword)]

    /**
     * The generic Forge enum name is insufficient for a small set of keyword
     * families. Preserve their parameter only when GRE has an exact ability
     * type; all other keyword families retain their stable base display name.
     */
    fun projectionName(keyword: KeywordInterface): String =
        when (keyword.keyword) {
            Keyword.LANDWALK -> exactOrBaseKeyword(keyword, keyword.title)

            Keyword.HEXPROOF -> exactOrBaseKeyword(keyword, keyword.title)

            Keyword.PROTECTION,
            Keyword.AFFINITY,
            -> keyword.title

            Keyword.TYPECYCLING ->
                (keyword as? KeywordWithCostAndType)?.titleWithoutCost ?: keyword.keyword.toString()

            else -> keyword.keyword.toString()
        }

    private fun exactOrBaseKeyword(
        keyword: KeywordInterface,
        parameterizedName: String,
    ): String = if (forKeyword(parameterizedName) != null) parameterizedName else keyword.keyword.toString()

    /** Forge and GRE differ predictably in capitalization, spaces, and hyphens. */
    private fun lookupName(keyword: String): String =
        buildString(keyword.length) {
            for (character in keyword) {
                if (!character.isWhitespace() && character != '-') append(character.lowercaseChar())
            }
        }
}
