package leyline.game.codes

/** GRE AbilityType values used by both static keyword choices and temporary keyword grants. */
object KeywordGrpIds {
    /**
     * Forge keyword display names with one unambiguous GRE AbilityType counterpart.
     *
     * Generic families whose client identity depends on a parameter, such as Affinity, Protection,
     * and TypeCycling, are deliberately absent.
     */
    private val canonicalIds =
        mapOf(
            "Absorb" to 65,
            "Afflict" to 164,
            "Afterlife" to 173,
            "Aftermath" to 159,
            "Amplify" to 39,
            "Annihilator" to 87,
            "Ascend" to 165,
            "Aura swap" to 66,
            "Awaken" to 359,
            "Backup" to 287,
            "Banding" to 23,
            "Bargain" to 303,
            "Battle cry" to 92,
            "Bestow" to 335,
            "Blitz" to 240,
            "Bloodthirst" to 55,
            "Bushido" to 46,
            "Buyback" to 28,
            "Cascade" to 86,
            "Casualty" to 241,
            "Champion" to 73,
            "Changeling" to 74,
            "Choose a Background" to 389,
            "Cipher" to 100,
            "Companion" to 202,
            "Compleated" to 238,
            "Conspire" to 79,
            "Convoke" to 52,
            "Crew" to 156,
            "Cumulative upkeep" to 25,
            "Cycling" to 30,
            "Dash" to 274,
            "Daybound" to 216,
            "Deathtouch" to 1,
            "Decayed" to 214,
            "Defender" to 2,
            "Delve" to 67,
            "Devour" to 83,
            "Devoid" to 151,
            "Disguise" to 307,
            "Disturb" to 215,
            "Double Strike" to 3,
            "Double team" to 253,
            "Dredge" to 53,
            "Echo" to 31,
            "Embalm" to 160,
            "Emerge" to 147,
            "Enchant" to 4,
            "Enlist" to 261,
            "Entwine" to 43,
            "Epic" to 51,
            "Equip" to 5,
            "Escape" to 199,
            "Escalate" to 153,
            "Eternalize" to 163,
            "Evoke" to 75,
            "Evolve" to 101,
            "Exalted" to 84,
            "Exploit" to 222,
            "Extort" to 102,
            "Fabricate" to 154,
            "Fading" to 33,
            "Fear" to 38,
            "Firebending" to 379,
            "First Strike" to 6,
            "Flanking" to 26,
            "Flash" to 7,
            "Flashback" to 35,
            "Flying" to 8,
            "For Mirrodin" to 267,
            "Foretell" to 208,
            "Fortify" to 68,
            "Frenzy" to 69,
            "Fuse" to 103,
            "Gift" to 342,
            "Graft" to 59,
            "Gravestorm" to 70,
            "Harmonize" to 362,
            "Haste" to 9,
            "Haunt" to 56,
            "Hexproof" to 10,
            "Hideaway" to 76,
            "Horsemanship" to 32,
            "Impending" to 352,
            "Improvise" to 157,
            "Increment" to 404,
            "Indestructible" to 104,
            "Infect" to 91,
            "Ingest" to 144,
            "Intimidate" to 11,
            "Kicker" to 34,
            "Job select" to 364,
            "Jump-start" to 170,
            "Landwalk" to 16,
            "Level up" to 88,
            "Lifelink" to 12,
            "Living Weapon" to 93,
            "Madness" to 36,
            "Mayhem" to 383,
            "Melee" to 375,
            "Mentor" to 171,
            "Menace" to 142,
            "Megamorph" to 150,
            "Miracle" to 95,
            "Mobilize" to 363,
            "Modular" to 44,
            "Morph" to 37,
            "Multikicker" to 122,
            "Mutate" to 203,
            "Myriad" to 406,
            "Nightbound" to 217,
            "Ninjutsu" to 50,
            "Outlast" to 136,
            "Offering" to 49,
            "Offspring" to 341,
            "Overload" to 97,
            "Paradigm" to 405,
            "Partner" to 346,
            "Partner with" to 395,
            "Persist" to 80,
            "Phasing" to 27,
            "Plot" to 328,
            "Poisonous" to 71,
            "Prototype" to 263,
            "Provoke" to 40,
            "Prowess" to 137,
            "Prowl" to 77,
            "Rampage" to 24,
            "Reach" to 13,
            "Read ahead" to 260,
            "Rebound" to 89,
            "Recover" to 60,
            "Reconfigure" to 237,
            "Reinforce" to 78,
            "Renown" to 358,
            "Replicate" to 57,
            "Retrace" to 82,
            "Riot" to 175,
            "Ripple" to 61,
            "Saddle" to 329,
            "Scavenge" to 98,
            "Shadow" to 29,
            "Shroud" to 22,
            "Skulk" to 143,
            "Sneak" to 394,
            "Soulbond" to 96,
            "Soulshift" to 47,
            "Specialize" to 254,
            "Spectacle" to 174,
            "Splice" to 48,
            "Split second" to 62,
            "Spree" to 330,
            "Start your engines" to 354,
            "Starting intensity" to 249,
            "Station" to 373,
            "Storied" to 408,
            "Storm" to 41,
            "Sunburst" to 45,
            "Surge" to 356,
            "Suspend" to 63,
            "Teamwork" to 412,
            "Tiered" to 365,
            "Toxic" to 264,
            "Training" to 220,
            "Trample" to 14,
            "Transfigure" to 72,
            "Transmute" to 54,
            "Tribute" to 135,
            "Umbra armor" to 90,
            "Undying" to 94,
            "Unearth" to 85,
            "Unleash" to 99,
            "Vanishing" to 64,
            "Vigilance" to 15,
            "Ward" to 211,
            "Warp" to 371,
            "Web-slinging" to 382,
            "Wither" to 81,
        )

    private val idsByLookupName =
        canonicalIds.entries
            .associate { (name, id) -> lookupName(name) to id }
            .also { require(it.size == canonicalIds.size) { "Keyword lookup names must be unique" } }

    fun forKeyword(keyword: String): Int? = idsByLookupName[lookupName(keyword)]

    /** Forge and GRE differ predictably in capitalization, spaces, and hyphens. */
    private fun lookupName(keyword: String): String =
        buildString(keyword.length) {
            for (character in keyword) {
                if (!character.isWhitespace() && character != '-') append(character.lowercaseChar())
            }
        }
}
